CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    updated_date TIMESTAMP(6),
    email VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    updated_date TIMESTAMP(6),
    balance NUMERIC(38, 2) NOT NULL,
    wallet_number VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    updated_date TIMESTAMP(6),
    amount NUMERIC(38, 2) NOT NULL,
    description VARCHAR(255),
    recipient_wallet_number VARCHAR(255),
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    transaction_reference VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')),
    wallet_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);